### PR TITLE
Pete/fix warnings and format

### PR DESCRIPTION
**Pull request by pdietl**

### CODE REVIEW

**Comment by martonmiklos** [comment]
Well I am not a fan of the ST's coding style too, however I wondering if it would be useful to follow that. Just in case if they would release a new version of this API set it would be easier to merge their changes. But given the statistics (no release since the 1.0.0) I could drop this thought quite easily ;).

**Comment by pdietl** [comment]
Yeah. They made their library in a terrible way. I guess the cleanest option would be to not touch their code at all and make classes that inherit from their classes and implement the required functions. Ehhh. It's ugly no matter what.

**Comment by pdietl** [comment]
If they release another version, I'll personally port the code over

**Comment by martonmiklos** [comment]
> Yeah. They made their library in a terrible way. 

Uhm if you take into account that we did not needed to reverse engineer practically anything to implement the flashrom support for e.g. we could be grateful to them ;) Think about their code as a documentation.

> I guess the cleanest option would be to not touch their code at all and make classes that inherit from their classes and implement the required functions. Ehhh. It's ugly no matter what.

Well at some point I thought about rewriting it from scratch in C with libusb under an opensource license which could be bundled into flashrom, avrdude and the stlink. 

With the flashrom implementation I went this way, but that only covers the SPI functionality.  Back in the days I wondered about using GPIO for automated target connection detection, which could came handy at mass programming stuff with TAG connect: https://github.com/stlink-org/stlink/issues/1123 

I always have mixed feeling when touching/improving to these royality licensed stuff (like pk2cmd for e.g.): does it really the best investment to spend my spare time?

To be honest I planned the repo itself to be mainly serve the following purpose: raising awareness on the main point: i.e. you can use the stlinkv3 for many tricks without the ST's dll.
But do not misunderstand me: I am open to any positive contribution on this code.

**Comment by pdietl** [comment]
> Uhm if you take into account that we did not needed to reverse engineer practically anything to implement the flashrom support for e.g. we could be grateful to them ;) Think about their code as a documentation.

True. Maybe I was too harsh. I would say the code isn't _ideal_. But most things never are, are they? At least they gave us something. :)

**Comment by martonmiklos** [comment]
> If they release another version, I'll personally port the code over

@pdietl we have not talked for a while, I hope you are fine!

The day has come: there is a 1.2.0 version available 😆 
I am diffing it now, it looks that they will release STLink V4 soon.

**Pull request merged**
